repos:
  - repo: https://github.com/timothycrosley/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: '23.10.1'
    hooks:
      - id: black
        additional_dependencies: ['click==8.1.7']
        language_version: python3.10
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: Python style guide enforcement
        entry: flake8
        language: python
        types: [python]
  - repo: local
    hooks:
      - id: migrations
        name: migrations
        entry: pipenv run python manage.py makemigrations --dry-run --check
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true