version: '3'


volumes:
  minio-volume:

services:
  db:
    image: postgres:alpine
    volumes:
      - ./marketplace_db_master:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-volume:/data
    env_file:
      - .env
    command: server --console-address ":9001" /data

  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"