# Generated by Django 4.2.6 on 2024-03-04 16:11

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'article',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=512)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('on_sale', 'On Sale'),
                            ('out_of_stock', 'Out Of Stock'),
                        ],
                        default='out_of_stock',
                        max_length=32,
                    ),
                ),
                ('cost', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                (
                    'country_of_production',
                    django_countries.fields.CountryField(
                        blank=True, default='Ru', max_length=2, null=True
                    ),
                ),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'grades',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ('review', models.CharField(blank=True, max_length=1024, null=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='product.product',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'product_reviews',
                'verbose_name_plural': 'product_reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'picture',
                    models.ImageField(max_length=200, upload_to='product_photos/'),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='product.product',
                    ),
                ),
            ],
            options={
                'verbose_name': 'product_photo',
                'verbose_name_plural': 'product_photos',
            },
        ),
    ]
