# Generated by Django 4.2.6 on 2024-03-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('accounts', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_point',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='warehouse.deliverypoint',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='accounts.supplier'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'
            ),
        ),
    ]
