# Generated by Django 4.2.6 on 2024-03-04 16:11

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_address', models.CharField(max_length=512)),
                ('region', models.CharField(max_length=100)),
                ('confirm', models.BooleanField(default=False)),
                (
                    'country',
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('closed', 'Closed'),
                            ('prepare for the opening', 'Prepare For The Opening'),
                            ('prepare_to_close', 'Prepare To Close'),
                        ],
                        default='closed',
                        max_length=32,
                    ),
                ),
            ],
            options={
                'verbose_name': 'delivery_point',
                'verbose_name_plural': 'delivery_point',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_address', models.CharField(max_length=512)),
                ('region', models.CharField(max_length=100)),
                ('confirm', models.BooleanField(default=False)),
                (
                    'country',
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('closed', 'Closed'),
                            ('prepare for the opening', 'Prepare For The Opening'),
                            ('prepare_to_close', 'Prepare To Close'),
                        ],
                        default='closed',
                        max_length=32,
                    ),
                ),
            ],
            options={
                'verbose_name': 'warehouse',
                'verbose_name_plural': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='OrderingGoods',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'quantity',
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('assembly_stage', 'Assembly Stage'),
                            ('en_route', 'En Route'),
                            ('delivered', 'Delivered'),
                            ('сanceled', 'Canceled'),
                        ],
                        default='assembly_stage',
                        max_length=32,
                    ),
                ),
                (
                    'delivery_point',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='warehouse.deliverypoint',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='product.product',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='delivery_warehouse',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'
            ),
        ),
    ]
