# Generated by Django 4.2.6 on 2024-03-04 16:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        blank=True, default='', max_length=60, unique=True
                    ),
                ),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                (
                    'email',
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ('activation_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email_2fa', models.BooleanField(default=False)),
                (
                    'temporary_email',
                    models.CharField(blank=True, default='', max_length=50),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False,
                        help_text='''Designates whether this user should be treated
                         as active.Unselect this instead of deleting accounts.''',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('user', 'User'),
                            ('support', 'Support'),
                            ('admin', 'Admin'),
                        ],
                        default='user',
                        max_length=30,
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('confirm', models.BooleanField(default=False)),
                (
                    'confirmation_type',
                    models.CharField(
                        choices=[
                            ('sign_in', 'Sign In'),
                            ('sign_up', 'Sign Up'),
                            ('restore_password', 'Restore Password'),
                        ],
                        default='sign_in',
                        max_length=32,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('agent', models.CharField(max_length=256, null=True)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'LoginHistory',
                'verbose_name_plural': 'LoginHistory',
            },
        ),
        migrations.CreateModel(
            name='StaffMembers',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'date_of_employment',
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ('date_of_dismissal', models.DateTimeField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    'job_title',
                    models.CharField(
                        choices=[
                            ('support', 'Support'),
                            ('manager', 'Manager'),
                            ('warehouse_worker', 'Warehouse Worker'),
                            ('head_of_warehouse', 'Head Of Warehouse'),
                            ('delivery_point_worker', 'Delivery Point Worker'),
                            ('superuser', 'Super User'),
                        ],
                        default='support',
                        max_length=256,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=256)),
                (
                    'taxpayer_identification_number',
                    models.CharField(max_length=12, null=True, unique=True),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
